### ISSUE TITLE
I want to superscript and subscript some characters.

### ISSUE THREAD

**Issue by sanalms** [AliSoftware/OHAttributedLabel#37] opened 2011-08-21 05:35 UTC
is it possible by using this?. If possible could you please add examples?.

**Comment by AliSoftware** [comment] 2011-08-21 13:29
Nope, this is not possible.

You should have searched "superscript" in the existing issues first: this is a duplicate of issue #25, in which everything is explained why, even if in theory it is supported by CoreText, in practice no font embed in the iPhone support this.

See also commit 5dd7dba9273938dde10f1eeed05a2953fa9e6ba0 where I added this subscript/superscript (then later removed it as it was not working, according to what is said in the comments of this commit)

**Closed as completed by AliSoftware** 2011-08-21 13:29 UTC
